apiVersion: apps/v1
kind: Deployment
metadata:
  name: json-server
  namespace: portfolio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: json-server
  template:
    metadata:
      labels:
        app: json-server
    spec:
      imagePullSecrets:
        - name: ghcr-pull-secret
      containers:
        - name: json-server
          image: ghcr.io/stevedev7/portfolio-json-server:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3002
          volumeMounts:
            - name: data
              mountPath: /app/data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: json-server-data
