apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: json-server-data
  namespace: portfolio
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: json-server-data-pv
  storageClassName: ""
