apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin
  namespace: portfolio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin
  template:
    metadata:
      labels:
        app: admin
    spec:
      imagePullSecrets:
        - name: ghcr-pull-secret
      containers:
        - name: admin
          image: ghcr.io/stevedev7/portfolio-admin:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: API_UPSTREAM
              value: "http://api.portfolio.svc.cluster.local:3001"
            - name: MINIO_UPSTREAM
              value: "http://minio.minio.svc.cluster.local:9000/portfolio"

