apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin
  namespace: portfolio
spec:
  imagePullSecrets:
    - name: ghcr-pull-secret
  replicas: 1
  selector:
    matchLabels:
      app: admin
  template:
    metadata:
      labels:
        app: admin
    spec:
      containers:
        - name: admin
          image: ghcr.io/stevedev7/portfolio-admin:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
