apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: api-logs
  namespace: portfolio
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: api-logs-pv
  storageClassName: ""
