apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: portfolio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      imagePullSecrets:
        - name: ghcr-pull-secret
      containers:
        - name: web
          image: ghcr.io/stevedev7/portfolio-web:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: API_URL
              value: "http://api.portfolio.svc.cluster.local:3001"
